### ISSUE TITLE
Expanding the connector with other information

### ISSUE THREAD

**Issue by gijsvanbeek** [migueesc123/WooCommerceConnector#10]
Hello,

First of all thank you for this great custom connector!
I'm using it for a while now, and also wondered many times if you will be expanding to other WooCommerce tables, like customers, products etc.
i have recently expanded the connector so i can also read data from the customer table.
If you are interested maybe we can share ideas?

Grtz
Gijs
![WooCommerce_connector](https://user-images.githubusercontent.com/43177432/58486220-b8958f00-8165-11e9-9386-67a3ad0552a6.PNG)

**Comment by migueesc123** [comment]
Hey! 

The main reason behind this connector not having more fields is 3 fold:
- I'm pretty low on availability 
- This connector is mainly a sample connector to showcase what a Custom Connector can give you (even with Incremental refresh)
- The current call does provide all of the fact data (users who placed an order) and from this only set of calls I can create the other tables that I need without having to overload the system with more requests

The code could use some rework if you want it to be THE best code possible as my main goal with the first version was to simply get the orders and that was it.

I'm completely open to the idea of a pull / merge request. Just send it and I'll do my best to review the request as soon as I can.

**Comment by gijsvanbeek** [comment]
hello,

Thanks for the quick reply.

what do you mean exactly with that you can create the other tables with the current query?
The query gives me all the fields of the orders, but (for example) only the Customer ID (not other information about the customer)
So that's why i have changed your code to also get all other information about the customers (based on the customer Id of the order i can link it to the customer table)

One final question: Is the code based on incremental refresh? or always all the orders?

**Comment by migueesc123** [comment]
You can expand the Billing / Shipping Fields and create a Customer table from it. Also, depending on how your WooCommerce is set up, some useful information could also be stored within the meta_data field, but it completely depends on how you use it.

In regards to incremental refresh, here's my take on it using this exact custom connector:
https://www.poweredsolutions.co/2018/05/08/first-thoughts-on-power-bi-incremental-refresh/

**Comment by karenjoconnell** [comment]
Any chance the mez with the customers will be shared???

**Comment by migueesc123** [comment]
Hey!
I've added a new subscriptions function in the event that you have the woocommerce subscriptions plug in.

The repo is open to any pull / merge requests so if you wish to expand the connector, you can do so freely. I'll review the code submmitted as soon as i'm available.

**Comment by gijsvanbeek** [comment]
@Karenjoconnell this is the edited version with the customers table

[WooCommerce.zip](https://github.com/migueesc123/WooCommerceConnector/files/3969513/WooCommerce.zip)
