### ISSUE TITLE
Will not Close & Apply data into Power BI

### ISSUE THREAD

**Issue by jleahy82** [migueesc123/WooCommerceConnector#11]
I followed all of the instructions on setting up the connector, and it seemed to work.  I was even able to see all of the data pulled into Power Query, however, when I click Close & Apply, I am getting an error that says: 

Failed to save modifications to the server. Error returned: 'Expression in partition 'n/a' in table 'n/a' references unknown variable or function 'WooCommerce.Contents'.
 '.

Has anyone else ever run into this issue?  I feel like I am missing something simple.

![error](https://user-images.githubusercontent.com/62582329/77385824-a83b4a00-6d5f-11ea-9bd6-1dab3bfa5d1c.png)

**Comment by migueesc123** [comment]
Hey!
I had a different person that had a similar issue with a completely different custom connector.
You can see it here:
https://github.com/migueesc123/PowerBIRESTAPI/issues/28

I have no idea how it's being triggered or how to even reproduce it on my end. Can you try reproducing this on a completely new computer ? if you're able to reproduce, please let me know how you were able to do so.

**Comment by jleahy82** [comment]
Hi Miguel,

I just tried this on another computer, and received the same error.

Here is exactly what I did, step by step.

API is already enabled with WooCommerce.  We are able to pull the data from postman with no issues using the Consumer Key and Consumer Secret.

1.  Downloaded the WooCommerce.mez file
2.  Created the "Microsoft Power BI Desktop" folder and "Custom Connectors" sub folder in my documents
3. Opened Up Power BI.
4. Received a message stating that I need to change my security settings in order to use custom add-ins.
5. Change my Security settings to Allow any extensions to load without security validation or warning
![image](https://user-images.githubusercontent.com/62582329/77388692-323ae100-6d67-11ea-98fe-532d7e42072f.png)
6. While I was in my settings, I enabled the 2 new preview features that came out this month.
7. Clicked Get Data  > Picked "WooCommerce (Beta)"
8. Received warning about connecting to a third-party service, clicked continue
9. Added my url.  Choose my API version v3  (site was set up about 4 days ago)
10. Entered the Consumer Key and Consumer Secret.
11. Clicked Transform
12. The data comes in with no problem in Power Query.
13. Click on Close & Apply.

This is when the error pops up.  Not sure if there is something else I need to do with the security settings?  I captured a screenshot of my settings.

If there are any other steps that you need me to clarify, please don't hesitate to ask.

**Comment by migueesc123** [comment]
on step 10 to 11, did you select the function? or what exact object did you select from the navigator window?

**Comment by migueesc123** [comment]
forgot to include this, but is this happening with other custom connectors that you have in your computer? My best guess is that this is something happening with your Power BI Desktop installation which is causing this error for any custom connectors

**Comment by jleahy82** [comment]
This was my first custom connector that I have ever installed.  I will try and install another one to see if I get the same error. 

I may also try uninstalling Power BI, then re-installing the program to see if that helps.  I will let you know what I come up with.

**Comment by jleahy82** [comment]
Miguel,

I chose the orders between steps 10 & 11.  We are still using test data, so there are not that many transactions in here yet, but we are hoping to have the site live by the end of the week.  I was hoping that we could use Power BI for all of the report.
  
![image](https://user-images.githubusercontent.com/62582329/77459146-a4e2a580-6dd5-11ea-94f2-c27579063d1a.png)

I still haven't had a chance to test another custom connector, but plan to do that shortly.

**Comment by jleahy82** [comment]
I tried to add another custom connector, and received the same error, so I don't think that it has to do with this connector.  I have also uninstalled and reinstalled Power BI desktop and that did not help.  I will try and look for some solutions for this issue on blog.powerbi.com 

Thanks for your help.

**Comment by jleahy82** [comment]
I figured it out!!! It was one of the "preview features" that was breaking it.  I disabled all of the preview features, and now the connection is working!!!

It looks like it may have been the preview feature "Store datasets using enhanced metadata format" that was causing the issue.

**Comment by Oddjobe** [comment]
Hey @migueesc123 !
i got it to work bt doing two things.
First granting all permissions to the app
![image](https://user-images.githubusercontent.com/15087494/79793134-60084b00-8350-11ea-9b0f-c5f4c45e826a.png)
+
disabling the preview feature "Store datasets using enhanced metadata format".
Thanks for the tip and the great work you are doing.
