### ISSUE TITLE
Woocom Subscriptions

### ISSUE THREAD

**Issue by GWM2020** [migueesc123/WooCommerceConnector#12]
Hi Miguel, many thanks for this customised connector, it is great! I am struggling to bring in the subscription data table, it is only bringing in the order table information. The instructions doesn't seem to explain this.
I am new to PowerBI, so please explain it to me in simple terms. Thanks!

**Comment by migueesc123** [comment]
Hey! 
You are right. The .mez file in this repo doesn't contain the subscription endpoint, but the code in this repo does have it:
https://github.com/migueesc123/WooCommerceConnector/blob/master/Woocommerce/Woocommerce.pq

I've added a new .mez that does contain that version of the code to:
https://github.com/migueesc123/WooCommerceConnector/blob/master/WooCommerceWSubs.mez
