### ISSUE TITLE
Only 100 orders and 100 subscriptions being brought into PowerBI

### ISSUE THREAD

**Issue by GWM2020** [migueesc123/WooCommerceConnector#13]
Hi, many thanks for this connector. I installed it a few months back and it had been working perfectly. 
I have had to reconnect it and for some reason it  now only brings in a maximum of 100 orders from Woocommerce (as well as 100 subscriptions). This never use to be the case, so I was just wondering how to fix this?

Many thanks

**Comment by migueesc123** [comment]
Hey! 
I just tried this against my site and I can’t repro.
Could you try with a different site ? Could it be the actual site having some issues ?

**Comment by GWM2020** [comment]
Okay thanks for checking. I have replicated the issue on a testing site and it is bringing in more than 100 orders, so the issue must be with my site. 
Appreciate this is not an issue with your connector but in your experience do you have any pointers for things I should look for when troubleshooting?

**Comment by migueesc123** [comment]
It seems to be a server level issue, so the only thing that I can suggest is to have a WooCommerce expert check the services related to that plug in and how they’re running on your site.

I’ve never had an issue similar to it, but be sure to use the right WooCommerce API version or try upgrading your plug in.

**Comment by GWM2020** [comment]
Okay thank you for your help. Last question just to clarify, when you say 'check the services related to that plugin', which plugin do you mean?

**Comment by migueesc123** [comment]
Hey! Sorry. I’m referring to WooCommerce when I mention “that plug-in”
