### ISSUE TITLE
Advanced information from other WooCommerce tables

### ISSUE THREAD

**Issue by jirsbek** [migueesc123/WooCommerceConnector#3]
Hello, are there any plans for advanced information from WooCommerce tables? E.g. customers, products etc.?

Best regards

**Comment by migueesc123** [comment]
Hey,

I'm planning to revisit all of my custom connectors when the Data Gateway integration arrives which should be within the next few months. What other information would you like to see? most of  the information already comes from the orders, but the custom connector could def have other info if needed.

**Comment by jirsbek** [comment]
Thank you for your response. I would like to see more info about ordered products and customers (we've got several customer sale roles and capabilities) as well as order custom fields.

**Comment by migueesc123** [comment]
Thanks! Currently the connector does provide all of the order data, even customer information and all custom fields from each order. If you're not seeing these custom fields or you're getting errors please let me know. You should be able to see everything based on the WooCommerce API Documentation
