### ISSUE TITLE
schedulled refresh

### ISSUE THREAD

**Issue by dandaformanda** [migueesc123/WooCommerceConnector#4]
Hello, I have trouble with shedulling refresh.
I use woocommerce connector (beta)
Data Refresh in PBI Desktop works OK, but I can´t set shedulled refresh with PBI Gateway.
"You can't schedule refresh for this dataset because one or more sources currently don't support refresh."

Does this connector support schedulled refresh?
If not what would you recommend me how to continue.

Thank you
Daniel

**Comment by migueesc123** [comment]
Hey!

Currently, custom connectors can not be refreshed on the Power BI Service, but you can ask more information about when this would happen in the official Custom Connectors Repo [here](https://github.com/microsoft/dataconnectors).

What other users are using is a bunch of 3rd party tools that automatically refresh the PBIDesktop file locally and then places it on a SharePoint site or OneDrive Folder so you can see it on the service.

Once custom connectors support PBI Service refresh I'll update this connectors, so make sure that you're "watching" this repo to get notified once this happens.

**Comment by dandaformanda** [comment]
Thank you for this info although it is not a good one.
Can you name some of these 3rd party tools?

Thank you
Daniel

**Comment by migueesc123** [comment]
The most popular one is called Power Update, but I wouldn't be able to recommend any as I haven't tested any of them.
