### ISSUE TITLE
Publish Custom Data Connector to Web

### ISSUE THREAD

**Issue by GFWagnitz** [migueesc123/WooCommerceConnector#5]
Do you know if there's an official way to request publishing of a custom data connector to the web version of Power BI, so I can refresh the data once I send the .pibx file to the web version?

**Comment by migueesc123** [comment]
If you are the owner of the API or the service that you're querying, then you can go through the Power BI Service content pack program. In that program, they'll require you to create your own custom connector and they'll make it available on the service and hopefully on the desktop as well.
[Here's the link to that program](https://docs.microsoft.com/en-us/power-bi/developer/service-content-pack-overview).

I also commented on the issues that you raised on the official Microsoft DataConnectors repo
