### ISSUE TITLE
Getting "We cannot convert a value of type Record to type Table." Error

### ISSUE THREAD

**Issue by ermiaqasemi** [migueesc123/WooCommerceConnector#7]
Hi,

I am always getting this error 
![image](https://user-images.githubusercontent.com/2217080/53116140-eb503b80-3515-11e9-9281-71fe1bbc30dd.png)

how can I resolve this issue?

**Comment by migueesc123** [comment]
Hey!

I'm unable to replicate the issue on my end, but it might be related to this [line](https://github.com/migueesc123/WooCommerceConnector/blob/aa0adc02f27fb39ba251427da833cd762fb258f8/Woocommerce/Woocommerce.pq#L80)

You might need to accommodate the code to your specific WooCommerce environment and fields.
